(part "ABM8-20_000MHZ-B2-T"
    (packageRef "ABM810000MHZ12D2W")
    (interface
        (port "1" (symbPinId 1) (portName "X1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "GND_1") (portType INOUT))
        (port "3" (symbPinId 3) (portName "X2") (portType INOUT))
        (port "4" (symbPinId 4) (portName "GND_2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "171")
    (property "Mouser_Part_Number" "815-ABM8-20-B2-T")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/ABRACON/ABM8-20000MHZ-B2-T?qs=zLkLEWnxMJwLicGB81opDg%3D%3D")
    (property "Manufacturer_Name" "ABRACON")
    (property "Manufacturer_Part_Number" "ABM8-20.000MHZ-B2-T")
    (property "Description" "20 MHz +/-20ppm Crystal 18pF 50 Ohms 4-SMD, No Lead")
    (property "Datasheet_Link" "https://abracon.com/Resonators/abm8.pdf")
    (property "symbolName1" "ABM8-20_000MHZ-B2-T")
)
