(part "1N4148WS-HG3-08"
    (packageRef "SOD2713X115N")
    (interface
        (port "1" (symbPinId 1) (portName "K") (portType INOUT))
        (port "2" (symbPinId 2) (portName "A") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "122")
    (property "Mouser_Part_Number" "78-1N4148WS-HG3-08")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Vishay-Semiconductors/1N4148WS-HG3-08?qs=MLItCLRbWsz%2FnO5zs5RZvA%3D%3D")
    (property "Manufacturer_Name" "Vishay")
    (property "Manufacturer_Part_Number" "1N4148WS-HG3-08")
    (property "Description" "Diodes - General Purpose, Power, Switching 1V Vf, 4pF; 25nA Ir SOD-323")
    (property "Datasheet_Link" "")
    (property "symbolName1" "1N4148WS-HG3-08")
)
