(part "1761681-1"
    (packageRef "SHDR6W67P254_2X3_1524X916X922P")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "4") (portType INOUT))
        (port "5" (symbPinId 5) (portName "5") (portType INOUT))
        (port "6" (symbPinId 6) (portName "6") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Mouser_Part_Number" "571-1761681-1")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/TE-Connectivity/1761681-1?qs=BqFpTYCQ3dLAeZ2wzdz7aw%3D%3D")
    (property "Manufacturer_Name" "TE Connectivity")
    (property "Manufacturer_Part_Number" "1761681-1")
    (property "Description" "Body Features: Primary Product Color Black | Connector Profile Low | Daisy Chain With | Configuration Features: PCB Mount Orientation Vertical | Number of Positions 6 | Number of Rows 2 | Contact Features: Contact Mating Area Plating Material Thickness 15 MICIN | Contact Type Pin | PCB Contact Termination Area Plating Material Tin | Contact Base Material Phosphor Bronze | PCB Contact Termination Area Plating Material Thickness 100 MICIN | Contact Current Rating (Max) 1 AMP | Contact Underplating Material Ni")
    (property "Datasheet_Link" "https://www.te.com/commerce/DocumentDelivery/DDEController?Action=showdoc&DocId=Customer+Drawing%7F1761681%7FA1%7Fpdf%7FEnglish%7FENG_CD_1761681_A1.pdf%7F1761681-1")
    (property "symbolName1" "1761681-1")
)
