(part "ERA-6ARW472V"
    (packageRef "ERA6AEB101V")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "131")
    (property "Mouser_Part_Number" "667-ERA-6ARW472V")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Panasonic/ERA-6ARW472V?qs=ob%252BdNz2%252BYEgbYp9qzrbNPA%3D%3D")
    (property "Manufacturer_Name" "Panasonic")
    (property "Manufacturer_Part_Number" "ERA-6ARW472V")
    (property "Description" "Thin Film Resistors - SMD 0805 4.7Kohm 0.05% 10ppm AEC-Q200")
    (property "Datasheet_Link" "https://industrial.panasonic.com/cdbs/www-data/pdf/RDM0000/AOA0000C307.pdf")
    (property "symbolName1" "ERA-6ARW472V")
)
