(part "RN4871-I_RM130"
    (packageRef "RN4871")
    (interface
        (port "1" (symbPinId 1) (portName "NC") (portType INOUT))
        (port "2" (symbPinId 2) (portName "GND_1") (portType INOUT))
        (port "3" (symbPinId 3) (portName "P1_2") (portType INOUT))
        (port "4" (symbPinId 4) (portName "P1_3") (portType INOUT))
        (port "5" (symbPinId 5) (portName "P1_7") (portType INOUT))
        (port "6" (symbPinId 6) (portName "P1_6") (portType INOUT))
        (port "7" (symbPinId 7) (portName "UART_RX") (portType INOUT))
        (port "8" (symbPinId 8) (portName "UART_TX") (portType INOUT))
        (port "9" (symbPinId 9) (portName "P3_6") (portType INOUT))
        (port "10" (symbPinId 10) (portName "RST_N") (portType INOUT))
        (port "11" (symbPinId 11) (portName "P0_0") (portType INOUT))
        (port "12" (symbPinId 12) (portName "P0_2") (portType INOUT))
        (port "13" (symbPinId 13) (portName "GND_2") (portType INOUT))
        (port "14" (symbPinId 14) (portName "VBAT") (portType INOUT))
        (port "15" (symbPinId 15) (portName "P2_7") (portType INOUT))
        (port "16" (symbPinId 16) (portName "P2_0") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "579-RN4871IRM130")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Microchip-Technology/RN4871-I-RM130?qs=MLItCLRbWswoZsrzvVbGYw%3D%3D")
    (property "Manufacturer_Name" "Microchip")
    (property "Manufacturer_Part_Number" "RN4871-I/RM130")
    (property "Description" "Bluetooth BLE Module, Shielded, Antenna,")
    (property "Datasheet_Link" "http://ww1.microchip.com/downloads/en/DeviceDoc/50002489C.pdf")
    (property "symbolName1" "RN4871-I_RM130")
)
