(part "ADP3338AKCZ-5-R7"
    (packageRef "SOT230P700X180-4N")
    (interface
        (port "1" (symbPinId 1) (portName "GND") (portType INOUT))
        (port "2" (symbPinId 2) (portName "OUT_2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "IN") (portType INOUT))
        (port "4" (symbPinId 4) (portName "OUT") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "584-ADP3338AKCZ-5-R7")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Analog-Devices/ADP3338AKCZ-5-R7?qs=WIvQP4zGangs6Tv%252BSE3hsA%3D%3D")
    (property "Manufacturer_Name" "Analog Devices")
    (property "Manufacturer_Part_Number" "ADP3338AKCZ-5-R7")
    (property "Description" "Analog Devices ADP3338AKCZ-5-R7, LDO Voltage Regulator, 1A, 5 V +/-1.6%, 2.7  8 Vin, 3-Pin SOT-223")
    (property "Datasheet_Link" "")
    (property "symbolName1" "ADP3338AKCZ-5-R7")
)
