(part "RNCE0805BTE10K0"
    (packageRef "RESC2012X65N")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "131")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Manufacturer_Name" "Stackpole Electronics, Inc.")
    (property "Manufacturer_Part_Number" "RNCE0805BTE10K0")
    (property "Description" "Thin Film Resistors - SMD 10KOhms 0805 25ppm 1/8W 150V 0.1% Hi Temp/Stability")
    (property "Datasheet_Link" "https://www.mouser.sg/datasheet/2/418/9/ENG_DS_9_1773463_9_B-3355380.pdf")
    (property "symbolName1" "RNCE0805BTE10K0")
)
