(part "APT3216LSECK_J3-PRV"
    (packageRef "LEDC3216X95N")
    (interface
        (port "1" (symbPinId 1) (portName "K") (portType INOUT))
        (port "2" (symbPinId 2) (portName "A") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "122")
    (property "Mouser_Part_Number" "604-APT3216LSECKJ3RV")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Kingbright/APT3216LSECK-J3-PRV?qs=6oMev5NRZMH6FCB40E9NQw%3D%3D")
    (property "Manufacturer_Name" "Kingbright")
    (property "Manufacturer_Part_Number" "APT3216LSECK/J3-PRV")
    (property "Description" "3.2X1.6mm Low Current Red SMD LED; Water Clear; 625nm; 120 Viewing Angle")
    (property "Datasheet_Link" "https://componentsearchengine.com/Datasheets/1/APT3216LSECK_J3-PRV.pdf")
    (property "symbolName1" "APT3216LSECK_J3-PRV")
)
