(part "08053C334KAZ2A"
    (packageRef "CAPC2012X152N")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "32")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Manufacturer_Name" "Kyocera AVX")
    (property "Manufacturer_Part_Number" "08053C334KAZ2A")
    (property "Description" "AVX 330nF Multilayer Ceramic Capacitor (MLCC) 25 V 0805 SMT Max. Op. Temp. +125C")
    (property "Datasheet_Link" "")
    (property "symbolName1" "08053C334KAZ2A")
)
