(part "08055A300JAT2A"
    (packageRef "CAPC2012X94N")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "32")
    (property "Mouser_Part_Number" "581-08055A300J")
    (property "Mouser_Price/Stock" "https://www.mouser.com/Search/Refine.aspx?Keyword=581-08055A300J")
    (property "Manufacturer_Name" "Kyocera AVX")
    (property "Manufacturer_Part_Number" "08055A300JAT2A")
    (property "Description" "Multilayer Ceramic Capacitors MLCC - SMD/SMT 50V 30pF C0G 0805 5%")
    (property "Datasheet_Link" "https://componentsearchengine.com/Datasheets/1/08055A300JAT2A.pdf")
    (property "symbolName1" "08055A300JAT2A")
)
