(part "22-23-2021"
    (packageRef "SHDR2W87P0X254_1X2_493X635X1105P")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Mouser_Part_Number" "538-22-23-2021")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Molex/22-23-2021?qs=ILqg114nvd4YKlRlbo3yMg%3D%3D")
    (property "Manufacturer_Name" "Molex")
    (property "Manufacturer_Part_Number" "22-23-2021")
    (property "Description" "Headers & Wire Housings VERT PCB HDR 2P TIN FRICTION LOCK")
    (property "Datasheet_Link" "")
    (property "symbolName1" "22-23-2021")
)
