(part "dsPIC33FJ64MC804-I_ML"
    (packageRef "QFN65P800X800X100-45N-D")
    (interface
        (port "1" (symbPinId 1) (portName "SDA1/RP9/CN21/PMD3/RB9") (portType INOUT))
        (port "2" (symbPinId 2) (portName "PWM2H1/RP22/CN18/PMA1/RC6") (portType INOUT))
        (port "3" (symbPinId 3) (portName "PWM2L1/RP23/CN17/PMA0/RC7") (portType INOUT))
        (port "4" (symbPinId 4) (portName "RP24/CN20/PMA5/RC8") (portType INOUT))
        (port "5" (symbPinId 5) (portName "RP25/CN19/PMA6/RC9") (portType INOUT))
        (port "6" (symbPinId 6) (portName "VSS_1") (portType INOUT))
        (port "7" (symbPinId 7) (portName "VCAP") (portType INOUT))
        (port "8" (symbPinId 8) (portName "PGED2/PWM1H3/RP10/CN16/PMD2/RB10") (portType INOUT))
        (port "9" (symbPinId 9) (portName "PGEC2/PWM1L3/RP11/CN15/PMD1/RB11") (portType INOUT))
        (port "10" (symbPinId 10) (portName "PWM1H2/DAC1RP/RP12/CN14/PMD0/RB12") (portType INOUT))
        (port "11" (symbPinId 11) (portName "PWM1L2/DAC1RN/RP13/CN13/PMRD/RB13") (portType INOUT))
        (port "12" (symbPinId 12) (portName "TMS/PMA10/RA10") (portType INOUT))
        (port "13" (symbPinId 13) (portName "TCK/PMA7/RA7") (portType INOUT))
        (port "14" (symbPinId 14) (portName "PWM1H1/DAC1LP/RTCC/RP14/CN12/PMWR/RB14") (portType INOUT))
        (port "15" (symbPinId 15) (portName "PWM1L1/DAC1LN/RP15/CN11/PMCS1/RB15") (portType INOUT))
        (port "16" (symbPinId 16) (portName "AVSS") (portType INOUT))
        (port "17" (symbPinId 17) (portName "AVDD") (portType INOUT))
        (port "18" (symbPinId 18) (portName "%MCLR%") (portType INOUT))
        (port "19" (symbPinId 19) (portName "AN0/VREF+/CN2/RA0") (portType INOUT))
        (port "20" (symbPinId 20) (portName "AN1/VREF-/CN3/RA1") (portType INOUT))
        (port "21" (symbPinId 21) (portName "PGED1/AN2/C2IN-/RP0/CN4/RB0") (portType INOUT))
        (port "22" (symbPinId 22) (portName "PGEC1/AN3/C2IN+/RP1/CN5/RB1") (portType INOUT))
        (port "23" (symbPinId 23) (portName "AN4/C1IN-/RP2/CN6/RB2") (portType INOUT))
        (port "24" (symbPinId 24) (portName "AN5/C1IN+/RP3/CN7/RB3") (portType INOUT))
        (port "25" (symbPinId 25) (portName "AN6/DAC1RM/RP16/CN8/RC0") (portType INOUT))
        (port "26" (symbPinId 26) (portName "AN7/DAC1LM/RP17/CN9/RC1") (portType INOUT))
        (port "27" (symbPinId 27) (portName "AN8/CVREF/RP18/PMA2/CN10/RC2") (portType INOUT))
        (port "28" (symbPinId 28) (portName "VDD_1") (portType INOUT))
        (port "29" (symbPinId 29) (portName "VSS_2") (portType INOUT))
        (port "30" (symbPinId 30) (portName "OSC1/CLKI/CN30/RA2") (portType INOUT))
        (port "31" (symbPinId 31) (portName "OSC2/CLKO/CN29/RA3") (portType INOUT))
        (port "32" (symbPinId 32) (portName "TDO/PMA8/RA8") (portType INOUT))
        (port "33" (symbPinId 33) (portName "SOSCI/RP4/CN1/RB4") (portType INOUT))
        (port "34" (symbPinId 34) (portName "SOSCO/T1CK/CN0/RA4") (portType INOUT))
        (port "35" (symbPinId 35) (portName "TDI/PMA9/RA9") (portType INOUT))
        (port "36" (symbPinId 36) (portName "RP19/CN28/PMBE/RC3") (portType INOUT))
        (port "37" (symbPinId 37) (portName "RP20/CN25/PMA4/RC4") (portType INOUT))
        (port "38" (symbPinId 38) (portName "RP21/CN26/PMA3/RC5") (portType INOUT))
        (port "39" (symbPinId 39) (portName "VSS_3") (portType INOUT))
        (port "40" (symbPinId 40) (portName "VDD_2") (portType INOUT))
        (port "41" (symbPinId 41) (portName "PGED3/ASDA1/RP5/CN27/PMD7/RB5") (portType INOUT))
        (port "42" (symbPinId 42) (portName "PGEC3/ASCL1/RP6/CN24/PMD6/RB6") (portType INOUT))
        (port "43" (symbPinId 43) (portName "INT0/RP7/CN23/PMD5/RB7") (portType INOUT))
        (port "44" (symbPinId 44) (portName "SCL1/RP8/CN22/PMD4/RB8") (portType INOUT))
        (port "45" (symbPinId 45) (portName "EPAD") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "579-DSPIC364MC804IML")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Microchip-Technology/DSPIC33FJ64MC804-I-ML?qs=nMCt4TBfEwoppiYgos1DJw%3D%3D")
    (property "Manufacturer_Name" "Microchip")
    (property "Manufacturer_Part_Number" "dsPIC33FJ64MC804-I/ML")
    (property "Description" "MCU&DSP 64K Flash 16K RAM DMA QFN44")
    (property "Datasheet_Link" "http://ww1.microchip.com/downloads/en/DeviceDoc/70291G.pdf")
    (property "symbolName1" "dsPIC33FJ64MC804-I_ML")
)
