(part "B3F-1020"
    (packageRef "B3F1000")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "4") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "162")
    (property "Mouser_Part_Number" "653-B3F-1020")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Omron-Electronics/B3F-1020?qs=lK7M36XCk6J1%2FfWxwEHrqA%3D%3D")
    (property "Manufacturer_Name" "Omron Electronics")
    (property "Manufacturer_Part_Number" "B3F-1020")
    (property "Description" "Switch Tact SPST,flat 5mm act,PC Pins Black Plunger Tactile Switch, SPST-NO 0.05 A@ 24 V dc 0.9mm")
    (property "Datasheet_Link" "http://www.omron.com/ecb/products/pdf/en-b3f.pdf")
    (property "symbolName1" "B3F-1020")
)
