(part "0805YC106KAT2A"
    (packageRef "CAPC2012X94N")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "32")
    (property "Mouser_Part_Number" "581-0805YC106KAT2A")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/KYOCERA-AVX/0805YC106KAT2A?qs=3HJ2avRr9PKwMzeRMZhF2g%3D%3D")
    (property "Manufacturer_Name" "Kyocera AVX")
    (property "Manufacturer_Part_Number" "0805YC106KAT2A")
    (property "Description" "Multilayer Ceramic Capacitors MLCC - SMD/SMT 16V 10uF X7R 0805 10%")
    (property "Datasheet_Link" "https://www.mouser.fr/datasheet/2/40/AVX_X7RDielectric_777024-1853642.pdf")
    (property "symbolName1" "0805YC106KAT2A")
)
