(part "C0805J104K1RACAUTO"
    (packageRef "CAPC2012X140N")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "32")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Manufacturer_Name" "KEMET")
    (property "Manufacturer_Part_Number" "C0805J104K1RACAUTO")
    (property "Description" "SMD Auto X7R FO, Ceramic, 0.1 uF, 10%, 100 VDC, X7R, SMD, MLCC, Open Mode, Automotive Grade, 0805, 0.6 mm")
    (property "Datasheet_Link" "https://search.kemet.com/component-documentation/download/specsheet/C0805J104K1RACAUTO")
    (property "symbolName1" "C0805J104K1RACAUTO")
)
