(part "MBAST21GBC7475KTCA01"
    (packageRef "CAPC2114X145N")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "32")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Manufacturer_Name" "TAIYO YUDEN")
    (property "Manufacturer_Part_Number" "MBAST21GBC7475KTCA01")
    (property "Description" "4.7 F +/-10% 25V Ceramic Capacitor X7S 0805 (2012 Metric)")
    (property "Datasheet_Link" "https://ds.yuden.co.jp/TYCOMPAS/eu/detail?pn=MBAST21GBC7475KTCA01&u=I")
    (property "symbolName1" "MBAST21GBC7475KTCA01")
)
