(part "UA78M33CDCYG3"
    (packageRef "SOT230P700X180-4N")
    (interface
        (port "1" (symbPinId 1) (portName "INPUT") (portType INOUT))
        (port "2" (symbPinId 2) (portName "COMMON_1") (portType INOUT))
        (port "3" (symbPinId 3) (portName "OUTPUT") (portType INOUT))
        (port "4" (symbPinId 4) (portName "COMMON_2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "595-UA78M33CDCYG3")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/UA78M33CDCYG3?qs=0O%2FZFlpUpJU0kFSZAC76Kw%3D%3D")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "UA78M33CDCYG3")
    (property "Description" "Linear Voltage Regulators 3.3 V 500mA Fix Pos Voltage Regulator")
    (property "Datasheet_Link" "http://www.ti.com/lit/ds/symlink/ua78m.pdf")
    (property "symbolName1" "UA78M33CDCYG3")
)
